/*

    The virtual machine of the compiler which interprets amu's intermediate representation (AIR) bytecode
    as generated by Generator.

*/

#ifndef AMU_MACHINE_H
#define AMU_MACHINE_H

namespace amu {

struct CallFrame {
    BC* ip;
    u8* fp;
    Function* f;
}; 

struct Machine {
    // stack as an array of bytes
    u8* stack;
    u8* sp;

    Array<CallFrame> frames;
    CallFrame frame;


    // ~~~~~~~ interface ~~~~~~~


    // creates a machine with some entry Code object
    // places the instruction pointer at the start of the code's AIR
    static Machine*
    create(Code* entry); 

    // begins execution of the code 
    void
    run();

    void
    print_stack();

    void
    print_frame_vars();
};

} // namespace amu

#endif // AMU_MACHINE_H