/*

    The virtual machine of the compiler which interprets amu's intermediate representation (AIR) bytecode
    as generated by Generator.

*/

#ifndef AMU_MACHINE_H
#define AMU_MACHINE_H

#include "representations/Frame.h"

namespace amu {

struct VM {
    // stack as an array of bytes
    u8* stack;
    u8* sp;

    Array<Frame> frames;
    Frame frame;
	
	// set false when the VM still has instructions left to
	// process. this is set true when the final frame of the 
	// VM is returned from.
	b32 finished;


    // ~~~~~~~ interface ~~~~~~~


    // creates a VM with some entry Code object
    // places the instruction pointer at the start of the code's AIR
    static VM*
    create(Code* entry); 

    void
    destroy();

	// executes one instruction and returns that instruction
	BC*
	step();

    // executes the code until it finishes or until a break instruction is encountered
	// returns 0 if the machine finished, otherwise returns the last instruction 
	// encountered
    BC*
    run();

    void
    print_stack();

    void
    print_frame_vars();
};

} // namespace amu

#endif // AMU_MACHINE_H
